
(define qq 
  (macro (x) 
    (define (constantp exp)
      (if (pairp exp) (eqp (car exp) 'quote) (not (symbolp exp))))
    (define (combine_skeletons left right exp)
      (cond
       ((and (constantp left) (constantp right)) 
	(if (and (eqvp (eval left) (car exp))
		 (eqvp (eval right) (cdr exp)))
	    (list 'quote exp)
	    (list 'quote (cons (eval left) (eval right)))))
       ((nullp right) (list 'list left))
       ((and (pairp right) (eqp (car right) 'list))
	(cons 'list (cons left (cdr right))))
       (else (list 'cons left right))))
    (define (expand_quasiquote exp nesting)
      (cond
       ((not (pairp exp)) 
	(if (constantp exp) exp (list 'quote exp)))
       ((and (eqp (car exp) 'unquote) (equalp (length exp) 2))
	(if (equalp nesting 0)
	    (second exp)
	    (combine_skeletons ''unquote
			       (expand_quasiquote (cdr exp) (min nesting 1))
			       exp)))
       ((and (eqp (car exp) 'quasiquote) (equalp (length exp) 2))
	(combine_skeletons ''quasiquote
			   (expand_quasiquote (cdr exp) (plus nesting 1))
			   exp))
       ((and (pairp (car exp))
	     (eqp (caar exp) 'unquote_splicing)
	     (equalp (length (car exp)) 2))
	(if (equalp nesting 0)
	    (list 'append (second (first exp))
		  (expand_quasiquote (cdr exp) nesting))
	    (combine_skeletons (expand_quasiquote (car exp) (min nesting 1))
			       (expand_quasiquote (cdr exp) nesting)
			       exp)))
       (else (combine_skeletons (expand_quasiquote (car exp) nesting)
				(expand_quasiquote (cdr exp) nesting)
				exp))))
    (expand_quasiquote x 0)))

